// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJ3ymBpcr_hQeOo63zLYHa3PBMFonNK0',
    appId: '1:797626748980:web:d64480885e3effd6a3ba61',
    messagingSenderId: '797626748980',
    projectId: 'map-fb337',
    authDomain: 'map-fb337.firebaseapp.com',
    storageBucket: 'map-fb337.appspot.com',
    measurementId: 'G-PKRXX1RP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzpOTug5h8_GWselSSDTwAWdMEOJ6JQw',
    appId: '1:797626748980:android:1cf3d33077dbf486a3ba61',
    messagingSenderId: '797626748980',
    projectId: 'map-fb337',
    storageBucket: 'map-fb337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLQbqkyVVIuWIsVLufTGc6ba5czEHYq4',
    appId: '1:797626748980:ios:d41f6dd1d49b2e30a3ba61',
    messagingSenderId: '797626748980',
    projectId: 'map-fb337',
    storageBucket: 'map-fb337.appspot.com',
    androidClientId: '797626748980-i7ut73petc33vi86ui93so00tuji513b.apps.googleusercontent.com',
    iosClientId: '797626748980-b6ubfbh63fq2t5ct35ee9qtu58dll1fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcLQbqkyVVIuWIsVLufTGc6ba5czEHYq4',
    appId: '1:797626748980:ios:559ca462d84367cfa3ba61',
    messagingSenderId: '797626748980',
    projectId: 'map-fb337',
    storageBucket: 'map-fb337.appspot.com',
    androidClientId: '797626748980-i7ut73petc33vi86ui93so00tuji513b.apps.googleusercontent.com',
    iosClientId: '797626748980-gllv7un5c7akhhqifdcb2qnv27h3ndff.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMap.RunnerTests',
  );
}
